### PR TITLE
Improve Dockerfiles to follow best practices

### PR DESCRIPTION
**Pull request by OompahLoompah**
This PR is composed of several changes to how we are currently handling the Dockerfiles for `./MANAGE` and `./WEB` to conform with best practices. Please see the individual commit details for more specific information.

### CODE REVIEW

**Comment by Procdox** [comment]
What is the reasoning for using copy over add?

edit: read provided documentation.

**Comment by Procdox** [comment]
I’m not sure why you’ve added constants.json to the ignore file, and copied it to the build folders?

**Comment by OompahLoompah** [comment]
@Procedurally-Unorthodox I explain in the commit messages. If you go to the `Commits` tab here and navigate to the individual commits you can see the associated messages.

**Comment by Procdox** [comment]
I noticed that after, sorry for redundant questions. I can test the build when I get off work. I’m not sure how I feel about the symlinking. The rest looks good.

**Comment by OompahLoompah** [comment]
No worries. :)

I was actually a bit conflicted myself because it requires a bit more housekeeping when creating new shared files. The developer would need to add the new file, new symlink, and dockerfile `COPY` command. The advantage we get though is increased clarity on what is exactly required for a container to run so it acts as a reminder to anyone making changes to `./SHARED` that they need to be aware a given file is in use and where specifically it's being used without needing to read every dockerfile.

**Comment by OompahLoompah** [comment]
Regarding testing, we honestly shouldn't be relying on manual tests. If there's no objection, I'd like to use circleci.com to run tests on PRs since there is a free plan for open-source projects. Also there's the advantage of the fact that I work there. :)

**Comment by Procdox** [comment]
I think it makes the file path a bit confusing. Introduces more housekeeping work, and most importantly, doesn’t work on windows! I think that, as there are only two services, it is given a file in shared must be used in both. Including all of shared is fine. And it implicitly clear that those files are relied upon by either service.

**Comment by OompahLoompah** [comment]
It would be more accurate to say, "it is given a file in shared must be used in both _for now_". I'm trying to advocate for this particular pattern because when the project complexity increases we are already being explicit about which files are used in which containers which increases clarity and prevents the copying of irrelevant files into containers.

**Comment by OompahLoompah** [comment]
Regarding the objection that symlinks don't work on windows, they're not required to in order to build the containers. They're literally just there to provide more explicit structure to the repo.

**Comment by OompahLoompah** [comment]
Sharing my objection to including the entirety of `./SHARED` in all containers here for posterity/transparency:

Let's say that we define a new docker container that uses some, but not all, of the shared resources. If we include all of `./SHARED` in that container and a file changes that it doesn't rely on it's still going to result in a rebuild of that docker layer. That would result in a wholly new container being built that needs to be pushed to wherever we host the containers even though nothing has changed in terms of operating the container.

The alternative would be to ignore those changes and suffer a longer build/test/deploy process for the sake of convenience. It can also add to confusion as to why the container built off of master is different from what is running in production/publicly available.

Containers should only ever contain exactly what they need to run. No more, no less. That philosophy is why it's best practice to use `alpine` as the base image instead of `ubuntu` or some other bloated container.

**Comment by OompahLoompah** [comment]
The more I think about this PR the more I realize `./SHARED` shouldn't even be included in the containers in the first place. Config shouldn't live in the container itself if it can be helped IMO unless there is a good reason for it. Config should be either pulled in or injected at container runtime. I'm closing this PR and will make a separate one for COPY over ADD in dockerfiles.

**Pull request closed without merging**
